export const dataHotelImage = [
  {
    imgUrl: "http://localhost:5000/hotel-booking-app/images/hotels/hotel1.jpg",
    hotelId: 1,
  },
  {
    imgUrl: "http://localhost:5000/hotel-booking-app/images/hotels/hotel2.jpg",
    hotelId: 1,
  },
  {
    imgUrl: "http://localhost:5000/hotel-booking-app/images/hotels/hotel3.jpg",
    hotelId: 1,
  },
  {
    imgUrl: "http://localhost:5000/hotel-booking-app/images/hotels/hotel4.jpg",
    hotelId: 1,
  },
  {
    imgUrl: "http://localhost:5000/hotel-booking-app/images/hotels/hotel5.jpg",
    hotelId: 1,
  },
  {
    imgUrl: "http://localhost:5000/hotel-booking-app/images/hotels/hotel6.jpg",
    hotelId: 1,
  },
  {
    imgUrl: "http://localhost:5000/hotel-booking-app/images/hotels/hotel7.jpg",
    hotelId: 1,
  },
  {
    imgUrl: "http://localhost:5000/hotel-booking-app/images/hotels/hotel8.jpg",
    hotelId: 1,
  },
  {
    imgUrl: "http://localhost:5000/hotel-booking-app/images/hotels/hotel9.jpg",
    hotelId: 2,
  },
  {
    imgUrl: "http://localhost:5000/hotel-booking-app/images/hotels/hotel10.jpg",
    hotelId: 2,
  },
  {
    imgUrl: "http://localhost:5000/hotel-booking-app/images/hotels/hotel11.jpg",
    hotelId: 2,
  },
  {
    imgUrl: "http://localhost:5000/hotel-booking-app/images/hotels/hotel12.jpg",
    hotelId: 2,
  },
  {
    imgUrl: "http://localhost:5000/hotel-booking-app/images/hotels/hotel13.jpg",
    hotelId: 2,
  },
  {
    imgUrl: "http://localhost:5000/hotel-booking-app/images/hotels/hotel14.jpg",
    hotelId: 2,
  },
  {
    imgUrl: "http://localhost:5000/hotel-booking-app/images/hotels/hotel15.jpg",
    hotelId: 2,
  },
  {
    imgUrl: "http://localhost:5000/hotel-booking-app/images/hotels/hotel16.jpg",
    hotelId: 2,
  },
  {
    imgUrl: "http://localhost:5000/hotel-booking-app/images/hotels/hotel17.jpg",
    hotelId: 3,
  },
  {
    imgUrl: "http://localhost:5000/hotel-booking-app/images/hotels/hotel18.jpg",
    hotelId: 3,
  },
  {
    imgUrl: "http://localhost:5000/hotel-booking-app/images/hotels/hotel19.jpg",
    hotelId: 3,
  },
  {
    imgUrl: "http://localhost:5000/hotel-booking-app/images/hotels/hotel20.jpg",
    hotelId: 3,
  },
  {
    imgUrl: "http://localhost:5000/hotel-booking-app/images/hotels/hotel21.jpg",
    hotelId: 3,
  },
  {
    imgUrl: "http://localhost:5000/hotel-booking-app/images/hotels/hotel22.jpg",
    hotelId: 3,
  },
  {
    imgUrl: "http://localhost:5000/hotel-booking-app/images/hotels/hotel23.jpg",
    hotelId: 3,
  },
  {
    imgUrl: "http://localhost:5000/hotel-booking-app/images/hotels/hotel24.jpg",
    hotelId: 3,
  },
  {
    imgUrl: "http://localhost:5000/hotel-booking-app/images/hotels/hotel25.jpg",
    hotelId: 4,
  },
  {
    imgUrl: "http://localhost:5000/hotel-booking-app/images/hotels/hotel26.jpg",
    hotelId: 4,
  },
  {
    imgUrl: "http://localhost:5000/hotel-booking-app/images/hotels/hotel27.jpg",
    hotelId: 4,
  },
  {
    imgUrl: "http://localhost:5000/hotel-booking-app/images/hotels/hotel28.jpg",
    hotelId: 4,
  },
  {
    imgUrl: "http://localhost:5000/hotel-booking-app/images/hotels/hotel29.jpg",
    hotelId: 4,
  },
  {
    imgUrl: "http://localhost:5000/hotel-booking-app/images/hotels/hotel30.jpg",
    hotelId: 4,
  },
  {
    imgUrl: "http://localhost:5000/hotel-booking-app/images/hotels/hotel31.jpg",
    hotelId: 4,
  },
  {
    imgUrl: "http://localhost:5000/hotel-booking-app/images/hotels/hotel32.jpg",
    hotelId: 4,
  },
  {
    imgUrl: "http://localhost:5000/hotel-booking-app/images/hotels/hotel33.jpg",
    hotelId: 5,
  },
  {
    imgUrl: "http://localhost:5000/hotel-booking-app/images/hotels/hotel34.jpg",
    hotelId: 5,
  },
  {
    imgUrl: "http://localhost:5000/hotel-booking-app/images/hotels/hotel35.jpg",
    hotelId: 5,
  },
  {
    imgUrl: "http://localhost:5000/hotel-booking-app/images/hotels/hotel36.jpg",
    hotelId: 5,
  },
  {
    imgUrl: "http://localhost:5000/hotel-booking-app/images/hotels/hotel37.jpg",
    hotelId: 5,
  },
  {
    imgUrl: "http://localhost:5000/hotel-booking-app/images/hotels/hotel38.jpg",
    hotelId: 5,
  },
  {
    imgUrl: "http://localhost:5000/hotel-booking-app/images/hotels/hotel39.jpg",
    hotelId: 5,
  },
  {
    imgUrl: "http://localhost:5000/hotel-booking-app/images/hotels/hotel40.jpg",
    hotelId: 5,
  },
  {
    imgUrl: "http://localhost:5000/hotel-booking-app/images/hotels/hotel41.jpg",
    hotelId: 6,
  },
  {
    imgUrl: "http://localhost:5000/hotel-booking-app/images/hotels/hotel42.jpg",
    hotelId: 6,
  },
  {
    imgUrl: "http://localhost:5000/hotel-booking-app/images/hotels/hotel43.jpg",
    hotelId: 6,
  },
  {
    imgUrl: "http://localhost:5000/hotel-booking-app/images/hotels/hotel44.jpg",
    hotelId: 6,
  },
  {
    imgUrl: "http://localhost:5000/hotel-booking-app/images/hotels/hotel45.jpg",
    hotelId: 6,
  },
  {
    imgUrl: "http://localhost:5000/hotel-booking-app/images/hotels/hotel46.jpg",
    hotelId: 6,
  },
  {
    imgUrl: "http://localhost:5000/hotel-booking-app/images/hotels/hotel47.jpg",
    hotelId: 6,
  },
  {
    imgUrl: "http://localhost:5000/hotel-booking-app/images/hotels/hotel48.jpg",
    hotelId: 6,
  },
  {
    imgUrl: "http://localhost:5000/hotel-booking-app/images/hotels/hotel41.jpg",
    hotelId: 7,
  },
  {
    imgUrl: "http://localhost:5000/hotel-booking-app/images/hotels/hotel42.jpg",
    hotelId: 7,
  },
  {
    imgUrl: "http://localhost:5000/hotel-booking-app/images/hotels/hotel43.jpg",
    hotelId: 7,
  },
  {
    imgUrl: "http://localhost:5000/hotel-booking-app/images/hotels/hotel44.jpg",
    hotelId: 7,
  },
  {
    imgUrl: "http://localhost:5000/hotel-booking-app/images/hotels/hotel45.jpg",
    hotelId: 7,
  },
  {
    imgUrl: "http://localhost:5000/hotel-booking-app/images/hotels/hotel46.jpg",
    hotelId: 7,
  },
  {
    imgUrl: "http://localhost:5000/hotel-booking-app/images/hotels/hotel47.jpg",
    hotelId: 7,
  },
  {
    imgUrl: "http://localhost:5000/hotel-booking-app/images/hotels/hotel48.jpg",
    hotelId: 7,
  },
  {
    imgUrl: "http://localhost:5000/hotel-booking-app/images/hotels/hotel33.jpg",
    hotelId: 8,
  },
  {
    imgUrl: "http://localhost:5000/hotel-booking-app/images/hotels/hotel34.jpg",
    hotelId: 8,
  },
  {
    imgUrl: "http://localhost:5000/hotel-booking-app/images/hotels/hotel35.jpg",
    hotelId: 8,
  },
  {
    imgUrl: "http://localhost:5000/hotel-booking-app/images/hotels/hotel36.jpg",
    hotelId: 8,
  },
  {
    imgUrl: "http://localhost:5000/hotel-booking-app/images/hotels/hotel37.jpg",
    hotelId: 8,
  },
  {
    imgUrl: "http://localhost:5000/hotel-booking-app/images/hotels/hotel38.jpg",
    hotelId: 8,
  },
  {
    imgUrl: "http://localhost:5000/hotel-booking-app/images/hotels/hotel39.jpg",
    hotelId: 8,
  },
  {
    imgUrl: "http://localhost:5000/hotel-booking-app/images/hotels/hotel40.jpg",
    hotelId: 8,
  },
];

export const dataHotel = [
  {
    name: "The Residences of The Ritz-Carlton Jakarta Pacific Place",
    place: "Jakarta",
    distance: 6.7,
    address: "Jalan Jendral Sudirman Kav. 52-53, 12190 Jakarta, Indonesia",
    offer: "Breakfast Included",
    roomDetails: "Luxury Room with Bath Tub",
    bedDetails: "1 king size single bed",
    roomLeft: 5,
    rating: 5,
    reviews: 312,
    night: 1,
    adult: 2,
    children: 1,
    price: 3150000,
  },
  {
    name: "Raffles Jakarta",
    place: "Jakarta",
    distance: 12,
    address: " Jalan Prof. Dr. Satrio Kav. 3-5, 12940 Jakarta, Indonesia ",
    offer: "Free Airport Taxi",
    roomDetails: "King Room with Bath Tub",
    bedDetails: "1 extra-large double bed",
    roomLeft: 3,
    rating: 5,
    reviews: 275,
    night: 1,
    adult: 2,
    children: 0,
    price: 3334000,
  },
  {
    name: "favehotel Tanah Abang - Cideng",
    place: "Jakarta",
    distance: 13.6,
    address:
      " Jl. Cideng Timur No. 58 Petojo Selatan, 10160 Jakarta, Indonesia",
    offer: " Free Laundry",
    roomDetails: "Superior Queen Room",
    bedDetails: "1 double bed",
    roomLeft: 2,
    rating: 3,
    reviews: 543,
    night: 2,
    adult: 2,
    children: 1,
    price: 428.0,
  },
  {
    name: "Sentral Cawang Hotel",
    place: "Jakarta",
    distance: 1.3,
    address: " Jl M.T. Haryono No 9, Cawang, 13630 Jakarta, Indonesia",
    offer: "Breakfast Included",
    roomDetails: "Deluxe Double Room",
    bedDetails: "1 large double bed",
    roomLeft: 3,
    rating: 3,
    reviews: 265,
    night: 1,
    adult: 2,
    children: 0,
    price: 408.0,
  },
  {
    name: "Maia Hotel Jakarta",
    place: "Jakarta",
    distance: 0.5,
    address: " 79 Jalan Kebon Kacang 9, 10240 Jakarta, Indonesia",
    offer: "Breakfast Included",
    roomDetails: "Superior Double Room",
    bedDetails: "1 large double bed",
    roomLeft: 5,
    rating: 4,
    reviews: 712,
    night: 1,
    adult: 2,
    children: 0,
    price: 2750000,
  },
  {
    name: "Novotel Jakarta Cikini",
    place: "Jakarta",
    distance: 4,
    address:
      " Jalan Cikini Raya No 107 109 Cikini Menteng Jakarta Pusat, 10330 Jakarta, Indonesia",
    offer: "Breakfast Included",
    roomDetails: "Deluxe Double Room",
    bedDetails: "1 large double bed",
    roomLeft: 3,
    rating: 4,
    reviews: 43,
    night: 2,
    adult: 2,
    children: 1,
    price: 3000000,
  },
  {
    name: "Bali ubud",
    place: "Bali",
    distance: 4,
    address:
      " Jalan Cikini Raya No 107 109 Cikini Menteng Jakarta Pusat, 10330 Jakarta, Indonesia",
    offer: "Breakfast Included",
    roomDetails: "Deluxe Double Room",
    bedDetails: "1 large double bed",
    roomLeft: 3,
    rating: 4,
    reviews: 43,
    night: 2,
    adult: 2,
    children: 1,
    price: 3000000,
  },
  {
    name: "The Residences of The Ritz-Carlton Jakarta Pacific Place",
    place: "Jakarta",
    distance: 6.7,
    address: "Jalan Jendral Sudirman Kav. 52-53, 12190 Jakarta, Indonesia",
    offer: "Breakfast Included",
    roomDetails: "Luxury Room with Bath Tub",
    bedDetails: "1 king size single bed",
    roomLeft: 5,
    rating: 5,
    reviews: 312,
    night: 1,
    adult: 2,
    children: 1,
    price: 3150000,
  },
  {
    name: "Raffles Jakarta",
    place: "Jakarta",
    distance: 12,
    address: " Jalan Prof. Dr. Satrio Kav. 3-5, 12940 Jakarta, Indonesia ",
    offer: "Free Airport Taxi",
    roomDetails: "King Room with Bath Tub",
    bedDetails: "1 extra-large double bed",
    roomLeft: 3,
    rating: 5,
    reviews: 275,
    night: 1,
    adult: 2,
    children: 0,
    price: 3334000,
  },
  {
    name: "favehotel Tanah Abang - Cideng",
    place: "Jakarta",
    distance: 13.6,
    address:
      " Jl. Cideng Timur No. 58 Petojo Selatan, 10160 Jakarta, Indonesia",
    offer: " Free Laundry",
    roomDetails: "Superior Queen Room",
    bedDetails: "1 double bed",
    roomLeft: 2,
    rating: 3,
    reviews: 543,
    night: 2,
    adult: 2,
    children: 1,
    price: 428000,
  },
  {
    name: "Sentral Cawang Hotel",
    place: "Jakarta",
    distance: 1.3,
    address: " Jl M.T. Haryono No 9, Cawang, 13630 Jakarta, Indonesia",
    offer: "Breakfast Included",
    roomDetails: "Deluxe Double Room",
    bedDetails: "1 large double bed",
    roomLeft: 3,
    rating: 3,
    reviews: 265,
    night: 1,
    adult: 2,
    children: 0,
    price: 408000,
  },
  {
    name: "Maia Hotel Bandung",
    place: "Bandung",
    distance: 0.5,
    address: " 79 Jalan Kebon Kacang 9, 10240 Jakarta, Indonesia",
    offer: "Breakfast Included",
    roomDetails: "Superior Double Room",
    bedDetails: "1 large double bed",
    roomLeft: 5,
    rating: 4,
    reviews: 712,
    night: 1,
    adult: 2,
    children: 0,
    price: 2750000,
  },
  {
    name: "Novotel Jakarta Cikini",
    place: "Jakarta",
    distance: 4,
    address:
      " Jalan Cikini Raya No 107 109 Cikini Menteng Jakarta Pusat, 10330 Jakarta, Indonesia",
    offer: "Breakfast Included",
    roomDetails: "Deluxe Double Room",
    bedDetails: "1 large double bed",
    roomLeft: 3,
    rating: 4,
    reviews: 43,
    night: 2,
    adult: 2,
    children: 1,
    price: 3000000,
  },
  {
    name: "Bali ubud",
    place: "Bali",
    distance: 4,
    address:
      " Jalan Cikini Raya No 107 109 Cikini Menteng Jakarta Pusat, 10330 Jakarta, Indonesia",
    offer: "Breakfast Included",
    roomDetails: "Deluxe Double Room",
    bedDetails: "1 large double bed",
    roomLeft: 3,
    rating: 4,
    reviews: 43,
    night: 2,
    adult: 2,
    children: 1,
    price: 3000000,
  },
];

export const dataHotelLocation = [
  { lat: 28.6048, lng: 77.2234, hotelId: 1 },
  { lat: 28.6289, lng: 77.0786, hotelId: 2 },
  { lat: 28.5516, lng: 77.1207, hotelId: 3 },
  { lat: 28.6448, lng: 77.2151, hotelId: 4 },
  { lat: 28.6338, lng: 77.2172, hotelId: 5 },
  { lat: 28.6613, lng: 77.1944, hotelId: 6 },
  { lat: 28.6613, lng: 77.1944, hotelId: 7 },
  { lat: 28.6338, lng: 77.2172, hotelId: 8 },
];
